# Generated by Django 2.2.16 on 2022-03-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220313_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка, загружаемая к посту', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
